version: "3.8"
services:
    centos-python:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "${PORT}:5000"
        depends_on:
          - arangodb
        volumes:
            - ${PROJECT_RELATIVE_PATH}:/github-connector:delegated
    arangodb:
      image: library/arangodb:3.6.3
      environment:
        ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD}
      ports:
        - "${ARANGODB_PORT}:8529"
      command: arangod --http.trusted-origin "*"
